resources:
  - name: pivotal-source
    type: git
    source:
      uri: https://github.com/greenplum-db/pgadmin4.git
#      branch: query-results-patch
#      branch: test-ci-error
      branch: test-ci-master
  - name: pipeline-ci
    type: git
    source:
      uri: https://github.com/greenplum-db/pgadmin4-ci.git
      branch: concourse

jobs:
- name: javascript-tests
  plan:
  - aggregate:
    - get: pivotal-source
      trigger: true
    - get: pipeline-ci
      trigger: true
  - task: karma-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: fotomut/pgadmin4, tag: 'python-3.6'}
      inputs:
        - name: pivotal-source
        - name: pipeline-ci
      run:
        path: pipeline-ci/tasks/run_karma.sh

- name: Python-3.6-Postgres
  plan:
  - aggregate:
    - get: pivotal-source
      trigger: true
      passed: [javascript-tests]
    - get: pipeline-ci
  - task: python-3.6-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: fotomut/pgadmin4, tag: 'python-3.6'}
#        source: {repository: markadams/chromium-xvfb-py3, tag: 'latest-onbuild'}
      inputs:
        - name: pivotal-source
        - name: pipeline-ci
      run:
        path: pipeline-ci/tasks/run_python_tests.sh
