---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: robdimsdale/concourse-pipeline-resource
    tag: latest-final

inputs:
  - name: pipeline-ci
  - name: source-branches
  - name: feature-branch-pipeline

outputs:
  - name: branch-jobs

run:
  path: sleep
  args: [10]
