resource_types:
- name: git-branches
  type: docker-image
  source: {repository: vito/git-branches-resource}
- name: concourse-pipeline
  type: docker-image
  source:
    repository: robdimsdale/concourse-pipeline-resource
    tag: latest-final

resources:
  - name: pgadmin-ci
    type: git
    source:
      uri: https://github.com/greenplum-db/pgadmin4-ci.git
      branch: master
  - name: source-branches
    type: git-branches
    source:
      uri: https://github.com/greenplum-db/pgadmin4.git
  - name: pgadmin-feature-branches
    type: concourse-pipeline
    source:
      target: {{concourse_url}}
      teams:
      - name: pgadmin
        username: {{concourse_user}}
        password: {{concourse_pw}}

jobs:
- name: pipeline-generation-tests
  public: true
  plan:
    - get: pgadmin-ci
      trigger: true
    - task: ruby-specs
      file: pgadmin-ci/pipelines/tasks/test-feature-branch-pipeline-generation.yml

- name: manually-generate-feature-branch-pipeline
  public: true
  plan:
  - aggregate:
    - get: pgadmin-ci
      trigger: false
      passed: [pipeline-generation-tests]
    - get: source-branches
  - task: generate-pipeline
    file: pgadmin-ci/pipelines/tasks/generate-feature-branch-pipeline.yml
    params:
      GPDB_HOST: {{gpdb_host}}
      GPDB_USERNAME: {{gpdb_username}}
      GPDB_PASSWORD: {{gpdb_password}}
      GPDB_PORT: {{gpdb_port}}
      PWS_USERNAME: {{pws_username}}
      PWS_PASSWORD: {{pws_password}}
      PWS_ORG: {{pws_org}}
      PWS_SPACE: {{pws_space}}
      TRACKER_TOKEN: {{tracker_token}}
  - put: pgadmin-feature-branches
    params:
      pipelines:
      - name: pgadmin-feature-branches
        team: main
        config_file: generated-pipelines/feature-branch-pipeline.yml
        vars_files:
        - generated-pipelines/concourse-config.yml
