resource_types:
- name: git-branches
  type: docker-image
  source: {repository: vito/git-branches-resource}
- name: concourse-pipeline
  type: docker-image
  source:
    repository: robdimsdale/concourse-pipeline-resource
    tag: latest-final

resources:
  - name: pivotal-source
    type: git
    source:
      uri: https://github.com/greenplum-db/pgadmin4.git
#      branch: query-results-patch
#      branch: test-ci-error
      branch: test-ci-master
  - name: pgadmin-ci
    type: git
    source:
      uri: https://github.com/greenplum-db/pgadmin4-ci.git
      branch: concourse
  - name: source-branches
    type: git-branches
    source:
      uri: https://github.com/greenplum-db/pgadmin4.git
  - name: resource-deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{cf_username}}
      password: {{cf_password}}
      organization: {{cf_org}}
      space: {{cf_space}}
      skip_cert_check: false
  - name: pgadmin-feature-branches
    type: concourse-pipeline
    source:
      target: {{concourse_url}}
      insecure: "true"
      teams:
      - name: main
        username: {{concourse_user}}
        password: {{concourse_pw}}

jobs:
- name: pipeline-generation-tests
  plan:
    - get: pgadmin-ci
      trigger: true
    - task: ruby-specs
      file: pgadmin-ci/pipelines/tasks/test-feature-branch-pipeline-generation.yml

- name: manually-generate-feature-branch-pipeline
  plan:
  - aggregate:
    - get: pgadmin-ci
      trigger: false
      passed: [pipeline-generation-tests]
    - get: source-branches
  - task: generate-pipeline
    file: pgadmin-ci/pipelines/tasks/generate-feature-branch-pipeline.yml
  - put: pgadmin-feature-branches
    params:
      pipelines:
      - name: pgadmin-feature-branches
        team: main
        config_file: generated-pipelines/feature-branch-pipeline.yml

- name: javascript-tests
  plan:
  - aggregate:
    - get: pivotal-source
      trigger: true
    - get: pipeline-ci
      trigger: true
  - task: karma-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: fotomut/pgadmin4, tag: 'python-3.6'}
      inputs:
        - name: pivotal-source
        - name: pipeline-ci
      run:
        path: pipeline-ci/tasks/run_karma.sh

- name: Python-3.6-Postgres
  plan:
  - aggregate:
    - get: pivotal-source
      trigger: true
      passed: [javascript-tests]
    - get: pipeline-ci
      trigger: true
      passed: [javascript-tests]
  - task: python-3.6-tests
    config:
      platform: linux
      outputs:
        - name: pws
          path: output
      image_resource:
        type: docker-image
#        source: {repository: fotomut/pgadmin4, tag: 'python-3.6'}
#        source: {repository: markadams/chromium-xvfb-py2, tag: 'latest-onbuild'}
#        source: {repository: justinribeiro/chrome-headless}
        source: {repository: joaopapereira/chrome-python-2.7.10, tag: 'latest'}
      inputs:
        - name: pivotal-source
        - name: pipeline-ci

      run:
        path: pipeline-ci/tasks/run_python_tests.sh
  - put: resource-deploy-web-app
    params:
      manifest: pws/manifest.yml
      path: pws
