platform: linux

image_resource:
  type: docker-image
  source:
    repository: appropriate/curl

inputs:
- name: pgadmin-repo-tarball
- name: pgadmin-ci
- name: build-metadata

run:
  path: pgadmin-ci/tasks/alert-slack/run.sh