platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/pgadmin
    tag: postgres-9.2

inputs:
- name: pgadmin-repo-tarball
- name: pgadmin-ci

run:
  path: pgadmin-ci/tasks/alert-slack/run.sh