platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfmanteiga/alpine-bash-curl-jq

inputs:
- name: pgadmin-repo-tarball
- name: pgadmin-ci

run:
  path: pgadmin-ci/tasks/alert-slack/run.sh
